#!/usr/bin/env bash

exec swaylock --screenshots --effect-blur 10x15 --ring-color 282828 --key-hl-color b8bb26 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 & 

(sleep 2 ; systemctl hibernate) &
